### ISSUE TITLE
ImportError: No module named 'six'

### ISSUE THREAD

**Issue by AllanLRH** [vim-zz/MiniPy#2]
MiniPy stopped working on my installation.
Using ST Dev Channel, Build 3125.

Tried to add it to ignored packages, then un-ignore it (in order to force a reload):

```
unloading plugin MiniPy.MiniPy
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["PersistentPython", "Python", "Python 3", "Vintage", "Vintageous"]
reloading plugin MiniPy.MiniPy
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MiniPy in /Users/allan/Library/Application Support/Sublime Text 3/Installed Packages/MiniPy.sublime-package", line 5, in <module>
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/arrow/all/arrow.py", line 11, in <module>
    from dateutil import tz as dateutil_tz
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/arrow/all/dateutil/tz.py", line 51, in <module>
    from six import string_types, PY3
ImportError: No module named 'six'
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by vim-zz** [comment]
1.1.x is broken I have reverted to 1.0.0, should fix this
